# -*- coding: utf8 -*-
#
# Copyright (C) 2020 NDP Syst√®mes (<http://www.ndp-systemes.fr>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
from odoo.addons.connector.exception import ConnectorException


class BadConnectorAnswerException(ConnectorException):
    def __init__(self, url, method, ans):
        self._url = url
        self._method = method
        self._ans = ans

    def __str__(self):
        return u"Error while doing %s on %s : %s" % (self._method, self._url, self._ans)
